### ISSUE TITLE
`nimble test` fails on Nim devel

### ISSUE THREAD

**Issue by narimiran** [bluenote10/NimSvg#1]
Here is the error message:

```
tester.nim(15, 7) template/generic instantiation of `suite` from here
tester.nim(17, 8) template/generic instantiation of `test` from here
tester.nim(18, 15) template/generic instantiation of `buildSvg` from here
../src/nimsvg.nim(199, 43) Error: illformed AST: 
```

This is line 199:
```nim
    result = getAst(appendElementNoChilren(tmp, tag, attributes))
```

It might be Nim regression, but can you please check it on your end first?

**Comment by bluenote10** [comment]
I tried to look into it, but I cannot reproduce the problem locally. I tried with a few days old Nim devel:

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-01-12
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 2ee2022c29ec4774eda51cb431052a9fc24982a7
active boot switches: -d:release
```

Any ideas how to reproduce it?

**Comment by narimiran** [comment]
> I tried with a few days old Nim devel

I had an older devel, so I just rebuilt it and the error is still there. To be sure, I've run both `nimble test` and `nim c -r tests/tester.nim` - both produce the same error reported above.

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-19
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 83f5839e2c1fa0c3c2c579c63eb52351a757d9cc
active boot switches: -d:release
```

**Comment by bluenote10** [comment]
Travis can reproduce the problem, I'll have to investigate why I couldn't reproduce it locally...
