### ISSUE TITLE
How to create a <text> element?

### ISSUE THREAD

**Issue by o5k4r** [bluenote10/NimSvg#3]
I'm trying to create the following element:

`<text x="40" y="35">sample</text>`

But I can't get the string "sample" at the right place.

The doc says nothing about it and reading the source did not help me neither, being new to the nim-lang.

Pls help, thanks
O5k4r

**Comment by bluenote10** [comment]
What you have to do is to prefix the text with a `t` to signal the DSL that you want a text node. For example:

```nim
import nimsvg

buildSvgFile("examples/basic1.svg"):
  svg(width=200, height=200, xmlns="http://www.w3.org/2000/svg", version="1.1"):
    text(x=100, y=100):
      t "sample"
```

Creating text node is still a bit experimental which is why I haven't documented this yet. Maybe there is a nicer solution.

**Comment by bluenote10** [comment]
I though it doesn't hurt to document this a little bit though.
