### ISSUE TITLE
Generating SVG programmatically

### ISSUE THREAD

**Issue by FedericoCeratto** [bluenote10/NimSvg#5]
NimSvg is very good at generating SVG declaratively using macros and templates, but sometimes the generation should be done dynamically based on parameters unknown at compile time.
Any help and example? Thanks

**Comment by bluenote10** [comment]
I don't fully understand what you mean. All the stuff going into the templates can be fully dynamic, right? For example, this program generates a circle with a radius specified at runtime from command line:

```nim
import nimsvg
import os
import strutils

let args = commandLineParams()
if args.len == 0:
  echo "No radius specified"
  quit 1

let r = parseFloat(args[0])

buildSvgFile("basic1.svg"):
  svg(width=200, height=200):
    circle(cx=100, cy=100, r=r, stroke="teal", `stroke-width`=4, fill="#DDD")
```

The whole animation part is based on rendering images dynamically.

**Comment by FedericoCeratto** [comment]
Creating a variable amount of elements (circles, rectangles, arrows) with the templates is awkward. Also, a common pattern requires rendering the SVG (e.g. to show it to the user), than change some of the element and render it again. Something like:
```
var g = svg(...)
g.add(some element)
let chart1 = g.render()
g.add(some element)
let chart2 = g.render()
```

**Comment by bluenote10** [comment]
> Creating a variable amount of elements (circles, rectangles, arrows) with the templates is awkward.

I really don't understand what you mean. Let's take an example that creates a variable number of circles:

```nim
proc createVariableNumberOfCircles(numCircles: int): Nodes =
  buildSvg:
    svg(width=200, height=200):
      for _ in 0 .. numCircles:
        circle(cx=random(size), cy=random(size), r=10)
```

There are no compile time constants. What is awkward about creating a variable amount of elements here, or what can be done to improve it?

If you are referring to doing stuff dynamically in the browser (dynamically updating the DOM) then NimSvg is not the right tool. That is what Karax is made for. The idea of NimSvg was to offer a similar DSL as Karax, but with extra convenience for generating local svg / gif files. If by "generating SVG programmatically" you mean DOM diffing, then Karax should be for you.

To some degree, programmatically generating SVG is always a bit awkward if that is what you mean (I just experimented with various JS solutions, and they all have their quirks as well). At least something like this can be done with reasonable effort:

![timeline_ex2](https://user-images.githubusercontent.com/3620703/79672465-8607e100-81d2-11ea-9d27-0fd79ac35a7c.gif)

**Comment by bluenote10** [comment]
Did you check out if Karax fits your use case?

I'll close the issue for the moment, feel free to re-open if desired ;)
